apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-intive-app27-pipeline-run-init
  namespace: demo-dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  
  labels:
    tekton.dev/pipeline: nodejs-intive-app27-pipeline
    janus-idp.io/tekton: nodejs-intive-app27
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/intive-RedHat-Devex-demo/nodejs-intive-app27.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/nodejs-deve-app/nodejs-intive-app27
  pipelineRef:
    name: nodejs-intive-app27-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
